name: laza
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.2.0
  text_responsive: ^1.2.1
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  injectable:
  get_it:
  animations: ^2.0.11
  firebase_auth: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator:
  build_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
flutter_intl:
  enabled: true
